TOP_DIR=$(XTENSA_OCL_TESTS_DIR)

HOST_SRC_CPP_FILES = test.cpp ${TOP_DIR}/Native/FFT2D_ref/fft2d_ref.cpp
DEVICE_SRC_CL_FILES =  FFT2D.cl 
DEVICE_OPTFLAGS = -mllvm -tensilica-misaligned-ldst-opt -mllvm -mao-allow-byte-idx-group=true
LDFLAGS=$(BIN)/host/FFT2D.a -L$(XTENSA_OCL_RT)/host/lib -lxocl-host-rt-sim-shared -Wl,-rpath=$(XTENSA_OCL_RT)/host/lib

include ../Makefile.x86_64-host
