TOP_DIR=$(XTENSA_OCL_TESTS_DIR)

HOST_SRC_CPP_FILES = test.cpp ${TOP_DIR}/Native/Integral_ref/Integral_ref.cpp
DEVICE_SRC_CL_FILES =  IntegralU8U32.cl

DEVICE_OPTFLAGS = -mllvm -tensilica-misaligned-ldst-opt -mllvm -mao-allow-byte-idx-group=true

LDFLAGS=$(BIN)/host/IntegralU8U32.a -L$(XTENSA_OCL_RT)/host/lib -lxocl-host-rt-sim-shared -Wl,-rpath=$(XTENSA_OCL_RT)/host/lib

include ../Makefile.x86_64-host

clean::
	rm -rf Output.yuv Input.yuv *gmon*
