TOP_DIR=$(XTENSA_OCL_TESTS_DIR)

HOST_SRC_CPP_FILES = test.cpp ${TOP_DIR}/Native/matMul_int_ref/matrixmultiply_ref.cpp 
DEVICE_SRC_CL_FILES =  mat_mul_int.cl
HOST_CMD_ARGS?=128 128 128 1 1

DEVICE_OPTFLAGS = -mllvm -tensilica-misaligned-ldst-opt -mllvm -mao-allow-byte-idx-group=true

LDFLAGS=$(BIN)/host/mat_mul_int.a -L$(XTENSA_OCL_RT)/host/lib -lxocl-host-rt-sim-shared -Wl,-rpath=$(XTENSA_OCL_RT)/host/lib

include ../Makefile.x86_64-host


