TOP_DIR=$(XTENSA_OCL_TESTS_DIR)

HOST_SRC_CPP_FILES = test.cpp ${TOP_DIR}/Native/Gradiant_ref/Gradiant_ref.cpp
DEVICE_SRC_CL_FILES = GradiantInterleave.cl

LDFLAGS=$(BIN)/host/GradiantInterleave.a -L$(XTENSA_OCL_RT)/host/lib -lxocl-host-rt-sim-shared -Wl,-rpath=$(XTENSA_OCL_RT)/host/lib

DEVICE_OPTFLAGS = -mllvm -tensilica-misaligned-ldst-opt -mllvm -mao-allow-byte-idx-group=true

include ../Makefile.x86_64-host

clean::
	rm -rf output_dx.yuv output_dy.yuv Input.yuv *gmon*
