TOP_DIR=$(XTENSA_OCL_TESTS_DIR)

HOST_SRC_CPP_FILES = test.cpp ${TOP_DIR}/Native/PerspectiveTransform_ref/warpperspective_ref.cpp
DEVICE_SRC_CL_FILES =  perspective.cl

DEVICE_OPTFLAGS = -mllvm -tensilica-misaligned-ldst-opt

LDFLAGS=$(BIN)/host/perspective.a -L$(XTENSA_OCL_RT)/host/lib -lxocl-host-rt-sim-shared -Wl,-rpath=$(XTENSA_OCL_RT)/host/lib

include ../Makefile.x86_64-host

DEVICE_COMPILE_COMMON_FLAGS += --no-dma-promo

clean::
	rm -rf *gmon* OutputY.yuv
